### ISSUE TITLE
Dockerfile and docker-compose.yml are missing

### ISSUE THREAD

**Issue by DXist** [marina-haliem/AdaPool#1]
Thank you for excellent research and sharing the code!

The README mentions `docker-compose` commands but there is no `Dockerfile/docker-compose.yml` files in the repository.

Is it possible to add them? It will helpful to reproduce the results.

Thank you in advance!

**Comment by marina-haliem** [comment]
Thank you, @DXist , for your comment. I've added these missing files to the repository.

**Comment by DXist** [comment]
@marina-haliem thank you so much!
